- name: Deploy Maven Artifact
  hosts: web
  become: yes

  tasks:
    - name: copy JAR files
      copy:
        src: /var/lib/jenkins/workspace/mavenproj/maven-example/target/maven-example-1.0-SNAPSHOT.jar
        dest: /opt/maven-example-1.0-SNAPSHOT.jar

    - name: Run application
      shell: nohup java -jar /opt/maven-example-1.0-SNAPSHOT.jar &
